{% set version = "3.5.0" %}

package:
  name: threadpoolctl
  version: {{ version }}

source:
  url: https://github.com/joblib/threadpoolctl/archive/{{ version }}.tar.gz
  sha256: 3d941a397b35d15522d095173d06adeadc1d95f81f63b35e078e77b2d7c80401

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core >2,<4
    - wheel
  run:
    - python

{% set skip_tests = "" %}
{% set skip_tests = skip_tests + "test_controller_info_actualized or " %}
{% set skip_tests = skip_tests + "test_threadpool_limits_by_prefix or " %}
{% set skip_tests = skip_tests + "test_threadpool_limits_by_prefix or " %}
{% set skip_tests = skip_tests + "test_set_threadpool_limits_by_api or " %}
{% set skip_tests = skip_tests + "test_threadpool_limits_function_with_side_effect or " %}
{% set skip_tests = skip_tests + "test_threadpool_limits_manual_restore or " %}
{% set skip_tests = skip_tests + "test_threadpool_controller_limit or " %}
{% set skip_tests = skip_tests + "test_get_params_for_sequential_blas_under_openmp or " %}
{% set skip_tests = skip_tests + "test_nested_limits or " %}
{% set skip_tests = skip_tests + "test_threadpool_controller_as_decorator or " %}
{% set skip_tests = skip_tests + "check_blas_num_threads" %}

test:
  source_files:
    tests
  requires:
    - pip
    - numpy
    - pytest
  imports:
    - threadpoolctl
  commands:
    - pip check
    - python -m threadpoolctl -i numpy

    - pytest -v tests                              # [not (aarch64 or s390x or (osx and x86_64))]
    # linux-aarch64 (neoversen1) and s390x (z14) are unrecognized
    # architectures on Prefect.  linux-aarch64 (m1) is perfectly OK.
    - pytest -v tests -k 'not test_architecture'   # [aarch64 or s390x]
    # osx-64 gets a dozen FAILURES
    - pytest -v tests -k "not ({{ skip_tests }})"  # [osx and x86_64]

about:
  home: https://github.com/joblib/threadpoolctl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python helpers to control the threadpools of native libraries
  description: |
    Python helpers to introspect and limit the number of threads used
    in native libraries that handle their own internal threadpool
    (BLAS and OpenMP implementations).
  doc_url: https://github.com/joblib/threadpoolctl
  dev_url: https://github.com/joblib/threadpoolctl

extra:
  recipe-maintainers:
    - ogrisel
    - tomMoral
    - jeremiedbb
